#port
server:
  port: 8080
#spring
spring:
  application:
    name: orderserver
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-order
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#eureka地址
eureka:
  client:
    registry-fetch-interval-seconds: 10 # 心跳间隔时间
    lease-renewal-interval-in-seconds: 15 # 租约更新间隔时间
    lease-expiration-duration-in-seconds: 45 # 租约到期时间
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

