#port
server:
  port: 5673
#spring
spring:
  application:
    name: mqserver
  rabbitmq:
    # 主机ip，修改成实际rabbitmq配置
    host: 127.0.0.1
    # 端口，修改成实际rabbitmq配置
    port: 5672
    # 用户名，修改成实际rabbitmq配置
    username: guest
    # 用户密码，修改成实际rabbitmq配置
    password: guest
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver